# Generated by Django 4.2.20 on 2025-04-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_bitrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitrixtoken',
            options={'verbose_name': 'Bitrix24 Token', 'verbose_name_plural': 'Bitrix24 Tokens'},
        ),
        migrations.AddField(
            model_name='bitrixtoken',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bitrixtoken',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bitrixtoken',
            name='expires_at',
            field=models.DateTimeField(default='2025-01-01 12:00:00'),
            preserve_default=False,
        ),
    ]
