# Generated by Django 4.2.20 on 2025-04-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_bitrix', '0002_alter_bitrixtoken_options_bitrixtoken_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=20)),
            ],
        ),
    ]
